### ISSUE TITLE
Change Renderer interface to satisfy go lint

### ISSUE THREAD

**Issue by mholt** [russross/blackfriday#240] opened 2016-02-14 06:40 UTC
I know this sounds a bit pedantic, but the `Renderer` interface has two methods that `golint` complains about: `BlockHtml` and `RawHtmlTag`. It suggests `BlockHTML` and `RawHTMLTag`.

FWIW I'm working to improve our [score on Go Report Card](https://goreportcard.com/report/github.com/mholt/caddy#golint)... :smile:

**Comment by shurcooL** [comment] 2016-02-14 07:34
It's a valid issue, but I'm afraid it might be a non-starter because it'd invalidate all implementations of the interface, which is a huge breaking API change. It's definitely not worth the cost to fix 2 minor lint issues.

I think this is an issue that should be resolved with the `v2` work which will break API compatibility and make many other desired improvements. See #218.

**Comment by mholt** [comment] 2016-02-14 14:48
Version 2 sounds good to me :+1:

**Comment by Ambrevar** [comment] 2016-10-05 05:44
This issue can be closed I believe.

**Comment by shurcooL** [comment] 2016-10-05 06:04
Confirmed, no longer an issue in `v2`, which this issue was tracking.

https://goreportcard.com/report/gopkg.in/russross/blackfriday.v2#golint

Closing.

**Closed by shurcooL** 2016-10-05 06:04 UTC
