### ISSUE TITLE
Implement HTML description lists

### ISSUE THREAD

**Issue by Alexis211** [russross/blackfriday#62] opened 2014-04-15 17:02 UTC
There is one syntax extension I had when using a PHP Markdown parser, that is the ability to write HTML description lists with the following syntax : 

    Cat
    : Fluffy animal everyone likes
    Internet
    : Vector of transmission for pictures of cats

The corresponding HTML output would be the following : 

    <dl>
    <dt>Cat</dt>
    <dd>Fluffy animal everyone likes</dd>
    <dt>Internet</dt>
    <dd>Vector of transmission for pictures of cats</dd>
    </dl>

Could you implement such a functionnality ? I would have done it myself, only I have no idea how your markdown parser works and how to modify it.

Keep up the good work !

**Comment by anthonyfok** [comment] 2015-09-26 04:39
Hurray!  This has been implemented by @vbatoufflet and merged by @rtfb in May–June 2015, so this Issue has been resolved and can be closed.  :-)

**Comment by shurcooL** [comment] 2015-09-26 05:20
Thanks for pointing that out, @anthonyfok.

Resolved in #171. Also duplicate of #144. Closing.

**Closed by shurcooL** 2015-09-26 05:20 UTC
